### ISSUE TITLE
Version info needed in the repository

### ISSUE THREAD

**Issue by MrJithil** [HdrHistogram/HdrHistogram_c#112]
Currently, there are no file/variable to identify the current version of the `histogram` package. Need to get the version from any of the file.

It could be something `#define CURRENT_VERSION = 0.11.6`. 

It will be more useful to maintain the version of dependancies where the `histogram` is being used.

**Comment by mikeb01** [comment]
The version is stored in the pkgconfig/hdr_histogram.pc file.  I can look into having the same value present in a header somewhere.

**Comment by marco-ippolito** [comment]
this would be very beneficial for the node.js project, I'd be interested in opening a PR if possible

**Comment by mikeb01** [comment]
Would be happy to receive this.  It would be useful to have some test or set it up a build parameter so that we don't have to update the version in multiple places.

**Comment by MrJithil** [comment]
Thanks For the PR.
