### ISSUE TITLE
segfault on decode

### ISSUE THREAD

**Issue by lfkerby** [HdrHistogram/HdrHistogram_c#22]
When performing a hdr_log_decode() on a moderately sized histogram output with hdr_log_encode I hit a segfault later in a malloc/free call.

Tracked it to an out of bounds overwrite in the counts array because the limit wasn't being set properly.

The attached patch fixes it for me (note that I've only tested the v2 encoding but the v1 code looks to be similarly broken).

**Comment by lfkerby** [comment]
hdr_histogram_log.c: fix decode error

    The sizeof the encoding header is included in the payload, so make sure we subtract it out
    when determining the counts limit.  Fixes out of bounds reference in counts array when
    decoding.

diff --git a/src/hdr_histogram_log.c b/src/hdr_histogram_log.c
index 5a4324f..570f1ac 100644
--- a/src/hdr_histogram_log.c
+++ b/src/hdr_histogram_log.c
@@ -525,7 +525,7 @@ static int hdr_decode_compressed_v1(
     }

     int32_t word_size = word_size_from_cookie(be32toh(encoding_flyweight.cookie));
-    int32_t counts_limit = be32toh(encoding_flyweight.payload_len) / word_size;
+    int32_t counts_limit = (be32toh(encoding_flyweight.payload_len) - sizeof(_encoding_flyweight_v1)) / word_size;
     int64_t lowest_trackable_value = be64toh(encoding_flyweight.lowest_trackable_value);
     int64_t highest_trackable_value = be64toh(encoding_flyweight.highest_trackable_value);
     int32_t significant_figures = be32toh(encoding_flyweight.significant_figures);
@@ -623,7 +623,7 @@ static int hdr_decode_compressed_v2(
     }

     int32_t word_size = 1;
-    int32_t counts_limit = be32toh(encoding_flyweight.payload_len);
+    int32_t counts_limit = be32toh(encoding_flyweight.payload_len) - sizeof(_encoding_flyweight_v1);
     int64_t lowest_trackable_value = be64toh(encoding_flyweight.lowest_trackable_value);
     int64_t highest_trackable_value = be64toh(encoding_flyweight.highest_trackable_value);
     int32_t significant_figures = be32toh(encoding_flyweight.significant_figures);

**Comment by mikeb01** [comment]
Hi, thank you for the bug report.  However, I think the bug is actually on the encoding side.  The payload length should not include the length of the encoding flyweight to be compatible with the Java implementation.

**Comment by lfkerby** [comment]
Yes, you are correct.  I found that late last night once I found/ran the tests and realized that the decode of the java generated log files was broken as well.  Was going to suggest a different fix this morning but you already found and fixed it similarly.
