### ISSUE TITLE
Make hdr_reset_internal_counters public

### ISSUE THREAD

**Issue by beberlei** [HdrHistogram/HdrHistogram_c#29]
I am using this function to implement a (de-)serialization for histograms, but its only defined in `hdr_test.h`, with the comment that its private. This API is however used inside `hdr_histogram.c`, so its not actually used only in tests.

Could you make it public in hdr_histogram.h? See https://github.com/beberlei/hdrhistogram-php/issues/8 for reference.

**Comment by remicollet** [comment]
+1

**Comment by mikeb01** [comment]
I didn't want to leak this function out to users outside of the hdr histogram, hence the lack of a prototype in the headers and instead including the prototype in the hdr_histogram_log.c.  Is there a reason why the serialisation provided in hdr_histogram_log.{h,c} isn't sufficient?  Are there some other use cases for this method that I'm missing?

I'm not dead-set against exposing this function, but would like to understand the use cases a bit more first.

**Comment by mikeb01** [comment]
It's been 5 months, but no follow-up to this issue therefore closing.

**Comment by beberlei** [comment]
@mikeb01 sorry for the late reply:

1. I reimplemented the serialization in the PHP library, because i wanted to convert the data to a structured PHP array that can then be serialized into anything, JSON, binary string or whatever else the user needs instead of forcing a base 64 encoded binary string, that cannot be processed further.

2. I added an optimization in the export, where he detects when the last bucket with items in it is found and skips everything above it. This way you can make the stored data much smaller, because we only rarely have outliers in the buckets on the high end.

This also leads to having to implement a import, which requires the reset method to function.
