### ISSUE TITLE
AIX Support

### ISSUE THREAD

**Issue by arienchen** [HdrHistogram/HdrHistogram_c#34]
Hi All,

Will it support AIX 6/7 in the future?

Sincerely,
ARIEN

**Comment by mikeb01** [comment]
There are no plans to support AIX at the moment.

Adding a new platform has 2 requirements.

1.   Initial patches to support the new platform.
1.   A system that can be used indefinitely to support continuous build and test as new versions are developed.

As an example, Windows support was recently added as a number of patches were supplied as a contribution and I was able to make use of AppVeyor to set up continuous integration for Windows.  I don't have access to any AIX machines either for development or testing, so until the above requirements are met we won't have AIX support.  Community contributions are welcome in this area.
