### ISSUE TITLE
Is it possible to build HdrHistogram_c under windows by using mingw?

### ISSUE THREAD

**Issue by xlong88** [HdrHistogram/HdrHistogram_c#38]

**Comment by mikeb01** [comment]
I haven't tried, but the build uses CMake which has MingGW support (https://cmake.org/cmake/help/v3.1/manual/cmake-generators.7.html#cmake-generators).  I don't have a Windows environment to test this, but I suspect that it should be a case of specifying the appropriate generator and running the build.  If you have the time to experiment and let me know how it goes then I can include that in the documentation.  It works okay with Visual Studio.

**Comment by xlong88** [comment]
I've tried, but it failed. I guess it might because of the winsock. When I changed the CMakelists to only using hdr_histogram.h and hdr_histogram.c. I succeeded the build.

"C:\Program Files (x86)\JetBrains\CLion 2016.2.3\bin\cmake\bin\cmake.exe" --build C:\Users\gtuser\.CLion2016.2\system\cmake\generated\HdrHistogram_c-3f1a26a5\3f1a26a5\Debug --target all -- -j 8
Scanning dependencies of target hdr_histogram_static
Scanning dependencies of target hdr_histogram
[  8%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_encoding.c.obj
[  8%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_encoding.c.obj
[ 12%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_histogram.c.obj
[ 16%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_histogram.c.obj
[ 20%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_histogram_log.c.obj
[ 25%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_histogram_log.c.obj
[ 29%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_interval_recorder.c.obj
[ 33%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_interval_recorder.c.obj
[ 37%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_thread.c.obj
[ 41%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_thread.c.obj
[ 50%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_time.c.obj
[ 50%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_time.c.obj
[ 54%] Building C object src/CMakeFiles/hdr_histogram_static.dir/hdr_writer_reader_phaser.c.obj
[ 58%] Building C object src/CMakeFiles/hdr_histogram.dir/hdr_writer_reader_phaser.c.obj
In file included from D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:35:0:
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c: In function 'hdr_encode_compressed':
D:\git-reps\testtest\HdrHistogram_c\src\hdr_endian.h:76:22: warning: implicit declaration of function 'htonll' [-Wimplicit-function-declaration]
 #  define htobe64(x) htonll(x)
                      ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:267:41: note: in expansion of macro 'htobe64'
     encoded->lowest_trackable_value   = htobe64(h->lowest_trackable_value);
                                         ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c: In function '_apply_to_counts_64':
D:\git-reps\testtest\HdrHistogram_c\src\hdr_endian.h:78:22: warning: implicit declaration of function 'ntohll' [-Wimplicit-function-declaration]
 #  define be64toh(x) ntohll(x)
                      ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:333:24: note: in expansion of macro 'be64toh'
         h->counts[i] = be64toh(counts_data[i]);
                        ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c: In function 'hdr_getline':
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:1037:12: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
     return getline(lineptr, &line_length, stream);
            ^
In file included from D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:35:0:
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c: In function 'hdr_encode_compressed':
D:\git-reps\testtest\HdrHistogram_c\src\hdr_endian.h:76:22: warning: implicit declaration of function 'htonll' [-Wimplicit-function-declaration]
 #  define htobe64(x) htonll(x)
                      ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:267:41: note: in expansion of macro 'htobe64'
     encoded->lowest_trackable_value   = htobe64(h->lowest_trackable_value);
                                         ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c: In function '_apply_to_counts_64':
D:\git-reps\testtest\HdrHistogram_c\src\hdr_endian.h:78:22: warning: implicit declaration of function 'ntohll' [-Wimplicit-function-declaration]
 #  define be64toh(x) ntohll(x)
                      ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:333:24: note: in expansion of macro 'be64toh'
         h->counts[i] = be64toh(counts_data[i]);
                        ^
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c: In function 'hdr_getline':
D:\git-reps\testtest\HdrHistogram_c\src\hdr_histogram_log.c:1037:12: warning: implicit declaration of function 'getline' [-Wimplicit-function-declaration]
     return getline(lineptr, &line_length, stream);
            ^
[ 62%] Linking C shared library libhdr_histogram.dll
[ 66%] Linking C static library libhdr_histogram_static.a
[ 66%] Built target hdr_histogram_static
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `hdr_encode_compressed':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:263: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:264: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:265: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:266: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:267: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:268: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:269: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:286: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:287: undefined reference to `__imp_htonl'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_16':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:315: undefined reference to `__imp_ntohs'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_32':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:324: undefined reference to `__imp_ntohl'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_64':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:333: undefined reference to `ntohll'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v0':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:419: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:436: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:442: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:443: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:444: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:445: undefined reference to `__imp_ntohl'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v1':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:514: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:531: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:537: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:538: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:539: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:540: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:541: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:570: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:571: undefined reference to `ntohll'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v2':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:612: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:629: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:635: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:636: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:637: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:638: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:671: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:672: undefined reference to `ntohll'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:706: undefined reference to `__imp_ntohl'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_histogram_log.c.obj): In function `hdr_getline':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:1037: undefined reference to `getline'
CMakeFiles\hdr_histogram.dir/objects.a(hdr_thread.c.obj): In function `hdr_usleep':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_thread.c:61: undefined reference to `__imp_select'
collect2.exe: error: ld returned 1 exit status
src\CMakeFiles\hdr_histogram.dir\build.make:259: recipe for target 'src/libhdr_histogram.dll' failed
mingw32-make.exe[2]: *** [src/libhdr_histogram.dll] Error 1
CMakeFiles\Makefile2:86: recipe for target 'src/CMakeFiles/hdr_histogram.dir/all' failed
mingw32-make.exe[1]: *** [src/CMakeFiles/hdr_histogram.dir/all] Error 2
mingw32-make.exe[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target hdr_histogram_test
Scanning dependencies of target hdr_decoder
Scanning dependencies of target hdr_histogram_log_test
Scanning dependencies of target perftest
[ 75%] Building C object examples/CMakeFiles/hdr_decoder.dir/hdr_decoder.c.obj
[ 75%] Building C object test/CMakeFiles/hdr_histogram_test.dir/hdr_histogram_test.c.obj
[ 83%] Building C object test/CMakeFiles/perftest.dir/hdr_histogram_perf.c.obj
[ 83%] Building C object test/CMakeFiles/hdr_histogram_log_test.dir/hdr_histogram_log_test.c.obj
D:\git-reps\testtest\HdrHistogram_c\test\hdr_histogram_log_test.c: In function 'compare_timespec':
D:\git-reps\testtest\HdrHistogram_c\test\hdr_histogram_log_test.c:69:13: warning: implicit declaration of function 'ctime_r' [-Wimplicit-function-declaration]
             ctime_r(&a->tv_sec, a_str),
             ^
[ 87%] Linking C executable hdr_decoder.exe
[ 91%] Linking C executable hdr_histogram_test.exe
[ 95%] Linking C executable hdr_histogram_log_test.exe
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_encode_compressed':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:263: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:264: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:265: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:266: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:267: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:268: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:269: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:286: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:287: undefined reference to `__imp_htonl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_16':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:315: undefined reference to `__imp_ntohs'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_32':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:324: undefined reference to `__imp_ntohl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_64':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:333: undefined reference to `ntohll'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v0':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:419: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:436: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:442: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:443: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:444: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:445: undefined reference to `__imp_ntohl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v1':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:514: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:531: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:537: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:538: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:539: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:540: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:541: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:570: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:571: undefined reference to `ntohll'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v2':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:612: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:629: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:635: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:636: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:637: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:638: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:671: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:672: undefined reference to `ntohll'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:706: undefined reference to `__imp_ntohl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_getline':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:1037: undefined reference to `getline'
collect2.exe: error: ld returned 1 exit status
examples\CMakeFiles\hdr_decoder.dir\build.make:98: recipe for target 'examples/hdr_decoder.exe' failed
CMakeFiles\Makefile2:311: recipe for target 'examples/CMakeFiles/hdr_decoder.dir/all' failed
mingw32-make.exe[2]: *** [examples/hdr_decoder.exe] Error 1
mingw32-make.exe[1]: *** [examples/CMakeFiles/hdr_decoder.dir/all] Error 2
CMakeFiles\hdr_histogram_log_test.dir/objects.a(hdr_histogram_log_test.c.obj): In function `compare_timespec':
D:/git-reps/testtest/HdrHistogram_c/test/hdr_histogram_log_test.c:67: undefined reference to `ctime_r'
D:/git-reps/testtest/HdrHistogram_c/test/hdr_histogram_log_test.c:67: undefined reference to `ctime_r'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_encode_compressed':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:263: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:264: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:265: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:266: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:267: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:268: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:269: undefined reference to `htonll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:286: undefined reference to `__imp_htonl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:287: undefined reference to `__imp_htonl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_16':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:315: undefined reference to `__imp_ntohs'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_32':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:324: undefined reference to `__imp_ntohl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `_apply_to_counts_64':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:333: undefined reference to `ntohll'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v0':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:419: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:436: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:442: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:443: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:444: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:445: undefined reference to `__imp_ntohl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v1':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:514: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:531: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:537: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:538: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:539: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:540: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:541: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:570: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:571: undefined reference to `ntohll'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed_v2':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:612: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:629: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:635: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:636: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:637: undefined reference to `ntohll'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:638: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:671: undefined reference to `__imp_ntohl'
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:672: undefined reference to `ntohll'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_decode_compressed':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:706: undefined reference to `__imp_ntohl'
../src/libhdr_histogram_static.a(hdr_histogram_log.c.obj): In function `hdr_getline':
D:/git-reps/testtest/HdrHistogram_c/src/hdr_histogram_log.c:1037: undefined reference to `getline'
collect2.exe: error: ld returned 1 exit status
test\CMakeFiles\hdr_histogram_log_test.dir\build.make:99: recipe for target 'test/hdr_histogram_log_test.exe' failed
mingw32-make.exe[2]: *** [test/hdr_histogram_log_test.exe] Error 1
mingw32-make.exe[1]: *** [test/CMakeFiles/hdr_histogram_log_test.dir/all] Error 2
CMakeFiles\Makefile2:219: recipe for target 'test/CMakeFiles/hdr_histogram_log_test.dir/all' failed
[100%] Linking C executable perftest.exe
[100%] Built target hdr_histogram_test
[100%] Built target perftest
mingw32-make.exe: *** [all] Error 2
Makefile:159: recipe for target 'all' failed

**Comment by mikeb01** [comment]
I suspect I probably need a few #defines in the right places.  If you want to have a dig, have a look at where __CYGWIN__ is used and add the appropriate for MINGW.  Or I can have a look when I get a Windows machine to experiment with.

**Comment by xlong88** [comment]
It turns out in MinGW's winsock2.h, there is no macro for ntohll and htonll. Besides in MinGW's stdio.h, there is no getline, and no ctime_r is found in time.h!

**Comment by mikeb01** [comment]
Probably some additional hacking required to treat MingGW as another platform similar to the way Windows is handled and provide appropriate macros/functions to make up the missing functionality.

**Comment by chronoxor** [comment]
I have no problems with building HdrHistogram as a static library under MinGW with a following CMake script:

`
if(NOT TARGET HdrHistogram)

  # Module library
  file(GLOB SOURCE_FILES "HdrHistogram/src/*.c")
  if(NOT MSVC)
    set_source_files_properties(${SOURCE_FILES} PROPERTIES COMPILE_FLAGS "${COMMON_COMPILE_FLAGS} -Wno-implicit-function-declaration -Wno-incompatible-pointer-types")
  else()
    # C4146: unary minus operator applied to unsigned type, result still unsigned
    # C4200: nonstandard extension used : zero-sized array in struct/union
    # C4244: 'conversion' conversion from 'type1' to 'type2', possible loss of data
    set_source_files_properties(${SOURCE_FILES} PROPERTIES COMPILE_FLAGS "${PEDANTIC_COMPILE_FLAGS} /wd4146 /wd4200 /wd4244")
  endif()
  add_library(HdrHistogram ${SOURCE_FILES})
  target_include_directories(HdrHistogram PRIVATE "zlib" PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/zlib")
  target_link_libraries(HdrHistogram zlib)

  # Module folder
  set_target_properties(HdrHistogram PROPERTIES FOLDER modules/HdrHistogram)

endif()
`
