### ISSUE TITLE
Broken histogram after decoding when setting values outside range

### ISSUE THREAD

**Issue by beberlei** [HdrHistogram/HdrHistogram_c#4]
I am having a very weird problem, when I use "hdr_record_value(s)" with a value outside the range (see example using i+1). The iterator for the decoded version of this HDR will print nothing and the program will exit.

When I remove the "+1" inside the loop everything works fine.

I came accross this bug in my PHP extension when setting a value outside range would make "hdrhistogram_c" hang in what seems an infinite loop on iteration of the decoded hdr (High CPU).

Sorry that I could not find a better reproduce case for this yet:

```c
#include <stdbool.h>
#include <string.h>
#include <inttypes.h>
#include <hdr_histogram.h>
#include <hdr_histogram_log.h>

int main(int argc, char **argv)
{
	struct hdr_histogram *histogram, *new = NULL;
	struct hdr_iter iterator;
	hdr_init(1, 1000 * 60, 3, &histogram);

	for (int i = 1; i < (1000 * 60); i++) {
		hdr_record_values(histogram, i+1, ((1000*60)-i) / 10);
	}

	char *data;

	if (hdr_log_encode(histogram, &data) != 0) {
		printf("error");
		return 1;
	}

	if (hdr_log_decode(&new, data, strlen(data)) != 0) {
		printf("error2");
		return 2;
	}

	hdr_iter_init(&iterator, new);

	while (hdr_iter_next(&iterator) == true) {
		printf("%"PRIu64": %"PRIu64"\n", iterator.value_from_index, iterator.count_at_index);
	}
}
```

**Comment by mikeb01** [comment]
I've converted this to a unit test, but can't seem to reproduce the failure that you mention.  I did fix a minor sizing issue yesterday.  Can you update the very latest and try again?

**Comment by beberlei** [comment]
Ok, the problem is an infinite loop, try this patch to your test:

	diff --git a/test/hdr_histogram_log_test.c b/test/hdr_histogram_log_test.c
	index ead4b8e..8eec8d9 100644
	--- a/test/hdr_histogram_log_test.c
	+++ b/test/hdr_histogram_log_test.c
	@@ -563,9 +563,9 @@ static char* test_string_encode_decode_with_value_out_of_range()
	     struct hdr_histogram *histogram = NULL;
	     struct hdr_histogram *new = NULL;
	     struct hdr_iter iterator;
	-    hdr_init(1, 1000 * 60, 3, &histogram);
	+    hdr_init(1, 1000 * 60, 2, &histogram);
	 
	-    for (int i = 1; i < (1000 * 60); i++)
	+    for (int i = 1; i < (1000 * 60); i = i+10)
	     {
		 hdr_record_values(histogram, i + 1, ((1000*60)-i) / 10);
	     }

It will keep printing the same line, never terminating:

	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0
	65280: 0

**Comment by mikeb01** [comment]
Just running this one down.  I think it is an issue with the base64 encoding.  The zlib trailer seems to get lost/corrupt.
