### ISSUE TITLE
Add a hdr_interval_recorder example to README

### ISSUE THREAD

**Issue by giltene** [HdrHistogram/HdrHistogram_c#42]
It would be useful to have a simple example of using hdr_interval_recorder (recording, sampling, producing log output from sample) in the README, since it's [presumably] a common use pattern.

**Comment by giltene** [comment]
hiccup.c is a good example, I agree. But it also highlights the complexity of the current recorder API (needing to provide an update function in "user" code, exposing the internal histograms and needing to initialize them separately). Perhaps the real thing here is a wish for simpler, more encapsulated recorder. One that would encapsulate the internal details and only expose histograms when sampling an interval histogram from the recorder, or potentially to an update function if an advanced use case. I'd definitely want a direct value recording API on the recorder, aimed at the common case of recording values (without needing to provide a function).

**Comment by mikeb01** [comment]
That makes sense, it should be possible to add most (all) of that by layering on top on what is already there.  I'll have a hack at it this week.

**Comment by mikeb01** [comment]
Have a look at the API now, see if that is closer to what you are looking for.

**Comment by mikeb01** [comment]
Assuming this is okay, closing.
