### ISSUE TITLE
Incorrect start time in the header

### ISSUE THREAD

**Issue by orpiske** [HdrHistogram/HdrHistogram_c#44]
I noticed that the header generated by the C library contains an invalid start time entry. The issue can be reproduced by simply running the hiccup example:  

```
$ cat ~/tmp/reproducer.hdr 
#[foobar]
#[Histogram log format version 1.2]
#[StartTime: 4199232.004 (seconds since epoch), Wed Feb 14:27:12 GMT 1970]
"StartTimestamp","EndTimestamp","Interval_Max","Interval_Compressed_Histogram"
292663.168,292664.169,227.0,HISTFAAAAJp4nC2NsQ3CQBAE/5fjfDofp8c2BiMjOSagABISKkAUQEgBlEBOQEJntEEJPDIrjVaaDba/P+sQwiOMmfw7ZprN+xIOn1EUoEgGImICXJSYmSQRRJgaca88rUwssTJYq0Yt72oqXokzg5RIxYjd1Pnnkopq3+52w/UVb6f9+njeDq2ZIl9MM0vMMQM6FKjRcQSV2Za0wBe9gQxY
```

In the heather above, the Start Time is incorrectly displayed as "Wed Feb 14:27:12 GMT 1970". 

This invalid header seems to prevent the Java code from HdrHistogram to parse the file:

```
$ ~/code/java/HdrHistogram/HistogramLogProcessor -i ~/tmp/reproducer.hdr
       Value     Percentile TotalCount 1/(1-Percentile)

#[Mean    =         0.00, StdDeviation   =         0.00]
#[Max     =         0.00, Total count    =            0]
#[Buckets =           13, SubBuckets     =          256]
```

The issue seems to be caused because the timestamp value is initialized. Additionally the hdr_gettime function is not suitable for initializing the timestamp because it relies on CLOCK_MONOTONIC.

**Comment by mikeb01** [comment]
Good spot, patch merged.
