### ISSUE TITLE
Broken percentile computation

### ISSUE THREAD

**Issue by vlm** [HdrHistogram/HdrHistogram_c#5]
Built a simple test case to reproduce.

```
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include "hdr_histogram.h"

int main() {
    int measurements[] = {
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
    };
    struct {
        int lowest;
        int highest;
    } trackable_values[] = {
        { 80, 110 },
        { 1, 1000 },
        { 1, 100000 }
    };

    for(size_t tv = 0; tv < sizeof(trackable_values)/sizeof(trackable_values[0]); tv++) {
        struct hdr_histogram *h = 0;
        printf("=== Test %d: hdr_init(%d, %d)\n", (int)tv+1,
                trackable_values[tv].lowest, trackable_values[tv].highest);

        /* Initialize histogram library */
        int ret = hdr_init(trackable_values[tv].lowest,
                           trackable_values[tv].highest, 5, &h);
        assert(ret == 0);
        assert(h);

        /* Fill with values. */
        printf("Values:");        for(size_t i=0; i < sizeof(measurements)/sizeof(measurements[0]); i++) {
            printf(" %d", measurements[i]);
            hdr_record_value(h, measurements[i]);
        }

        printf("\nPercentiles = %d/%d (50%%/90%%)\n",
            (int)hdr_value_at_percentile(h, 0.50),
            (int)hdr_value_at_percentile(h, 0.90)
        );
        hdr_percentiles_print(h, stdout, 2, 1, CLASSIC);
    }

    return 0;
}
```

Expected hdr_value_at_percentile) to give some values inside the 90..100 range. Meanwhile, the function returns weird output (like hdr_value_at_percentile(, 0.5) == 127), see the attached log:

```
=== Test 1: hdr_init(80, 110)
Values: 90 91 92 93 94 95 96 97 98 99 100 90 91 92 93 94 95 96 97 98 99 100
Percentiles = 127/127 (50%/90%)
       Value   Percentile   TotalCount 1/(1-Percentile)

   127.00000     0.000000           22         1.00
   127.00000     1.000000           22          inf
#[Mean    =       96.000, StdDeviation   =        0.000]
#[Max     =      127.000, Total count    =           22]
#[Buckets =            1, SubBuckets     =       262144]
=== Test 2: hdr_init(1, 1000)
Values: 90 91 92 93 94 95 96 97 98 99 100 90 91 92 93 94 95 96 97 98 99 100
Percentiles = 90/90 (50%/90%)
       Value   Percentile   TotalCount 1/(1-Percentile)

    90.00000     0.000000            2         1.00
    92.00000     0.250000            6         1.33
    95.00000     0.500000           12         2.00
    96.00000     0.625000           14         2.67
    98.00000     0.750000           18         4.00
    98.00000     0.812500           18         5.33
    99.00000     0.875000           20         8.00
    99.00000     0.906250           20        10.67
   100.00000     0.937500           22        16.00
   100.00000     1.000000           22          inf
#[Mean    =       95.000, StdDeviation   =        3.162]
#[Max     =      100.000, Total count    =           22]
#[Buckets =            1, SubBuckets     =       262144]
=== Test 3: hdr_init(1, 100000)
Values: 90 91 92 93 94 95 96 97 98 99 100 90 91 92 93 94 95 96 97 98 99 100
Percentiles = 90/90 (50%/90%)
       Value   Percentile   TotalCount 1/(1-Percentile)

    90.00000     0.000000            2         1.00
    92.00000     0.250000            6         1.33
    95.00000     0.500000           12         2.00
    96.00000     0.625000           14         2.67
    98.00000     0.750000           18         4.00
    98.00000     0.812500           18         5.33
    99.00000     0.875000           20         8.00
    99.00000     0.906250           20        10.67
   100.00000     0.937500           22        16.00
   100.00000     1.000000           22          inf
#[Mean    =       95.000, StdDeviation   =        3.162]
#[Max     =      100.000, Total count    =           22]
#[Buckets =            1, SubBuckets     =       262144]
```

**Comment by mikeb01** [comment]
Thanks for the report.

This is a missing validation.  You shouldn't be able to create a histogram with the values 80 & 110.  The high value should be more than double the lower value.

**Comment by vlm** [comment]
@mikeb01 Values 2 & 110 do not work either.

**Comment by mikeb01** [comment]
Just spotted a small problem with the test:

    (int)hdr_value_at_percentile(h, 0.50),
    (int)hdr_value_at_percentile(h, 0.90)

Should be:

    (int)hdr_value_at_percentile(h, 50.0),
    (int)hdr_value_at_percentile(h, 90.0)

Results seem fairly sane:

    === Test 1: hdr_init(2, 110)
    Values: 90 91 92 93 94 95 96 97 98 99 100 90 91 92 93 94 95 96 97 98 99 100
    Percentiles = 95/99 (50%/90%)
           Value   Percentile   TotalCount 1/(1-Percentile)
    
        91.00000     0.000000            4         1.00
        93.00000     0.250000            8         1.33
        95.00000     0.500000           12         2.00
        97.00000     0.625000           16         2.67
        99.00000     0.750000           20         4.00
        99.00000     0.812500           20         5.33
        99.00000     0.875000           20         8.00
        99.00000     0.906250           20        10.67
       101.00000     0.937500           22        16.00
       101.00000     1.000000           22          inf
    #[Mean    =       95.545, StdDeviation   =        3.201]
    #[Max     =      101.000, Total count    =           22]
    #[Buckets =            1, SubBuckets     =       262144]

**Comment by vlm** [comment]
Try 99% and 2..100 range. Will return 101ms at 99%, instead of 100, like it does for 1..100 range.

```
=== Test 4: hdr_init(2, 100)
Values: 90 91 92 93 94 95 96 97 98 99 100 90 91 92 93 94 95 96 97 98 99 100
Percentiles = 95/99/101 (50%/90%/99%)
```

**Comment by giltene** [comment]
The 2 value in the 2..100 is not just the lowest end of the range. It's the lowest discernible value unit (i.e. any two values *may* be considered the same if they fall within less than +/- this value away from each other). You can think of it as "smallest bucket size" (the smallest bucket will actually be the highest power of two that is less than or equal to this number).

This means that 100 and 101 are equivalent values under this setting. You get 101ms for the percentile report because percentiles show the highest equivalent value for their level (since they are support to represent the value that the requested percent of values falls below).
