### ISSUE TITLE
Win32 build

### ISSUE THREAD

**Issue by ahwayakchih** [HdrHistogram/HdrHistogram_c#61]
While working on update to https://github.com/mcollina/native-hdr-histogram/pull/24, i updated to latest HDR source and noticed that Win32 build does not work without a patch:

https://github.com/mcollina/native-hdr-histogram/commit/c63e97151dcff9b9aed1d8ea5e4f5964c69be32f

Would it be possible to merge that change here, upstream? Everything else works fine AFAIK :).

**Comment by ahwayakchih** [comment]
Thanks!

**Comment by mikeb01** [comment]
I've pushed a fix, but I don't have a win32 platform to test against. If you could verify that would be appreciated.

**Comment by ahwayakchih** [comment]
I do not have windows either, but https://github.com/mcollina/native-hdr-histogram has appveyor configured, so when i updated sources there and created PR, build was started at https://ci.appveyor.com/project/mcollina/native-hdr-histogram/builds/24646032

It does not test whole project, because it uses only a copy of `src/` subdirectory, but still that's the main part.

Unfortunately, build seems to be broken after update. It was OK before, with src copy from 35c3f522dc6e335b42e73c3df0521da75369d5c0.

Any idea why?

**Comment by mikeb01** [comment]
I made a small error when I extracted the leading zero count function.

**Comment by ahwayakchih** [comment]
Thanks. I updated sources and new build is queued now at https://ci.appveyor.com/project/mcollina/native-hdr-histogram/builds/24646372

**Comment by ahwayakchih** [comment]
Looks like it's ok for both x86 and x64 now. At least with Node v8, but other versions should be ok too, if one works.
