### ISSUE TITLE
potential memory leak

### ISSUE THREAD

**Issue by bmacnaughton** [HdrHistogram/HdrHistogram_c#62]
the potential leak is that the following sequence will not free successfully allocated memory if only one of the allocations fails.

```
    counts = calloc((size_t) cfg.counts_len, sizeof(int64_t));
    histogram = calloc(1, sizeof(struct hdr_histogram));

    if (!counts || !histogram)
    {
        return ENOMEM;
    }
```

it's not likely to be serious in most cases because they will usually both succeed.

**Comment by mikeb01** [comment]
I've pushed a fix, but I don't have a win32 platform to test against.  If you could verify that would be appreciated.

**Comment by bmacnaughton** [comment]
sorry, i don't have a windows platform either. i have tried to get the tests running on a linux machine though and haven't been able to get them to compile - complaining about missing header files that are in hdrhistrogram_c/src. i set C_INCLUDE_PATH and got past that but then having trouble finding libraries, LD_LIBRARY_PATH didn't address that. i'm just getting my toes wet with cmake and make so probably am not understanding what i need to read to figure it out.

what sequence do you go through to test?

**Comment by mikeb01** [comment]
Sorry commented on the wrong issue.  It was meant for #61.
