### ISSUE TITLE
Add atomic value recording APIs

### ISSUE THREAD

**Issue by giltene** [HdrHistogram/HdrHistogram_c#67]
Given the prevalence of the recorder pattern, I often find it useful to have atomic recording into a histogram (thus supporting concurrent recording activity from multiple threads) that does not require other histogram operations to be concurrent-safe.

By "Atomic" I mean that the incrementing of counts will be atomic, and that the updating of min and max will be atomic, but NOT that the overall combined operation will appear atomic (no need for that). We DO want the combined operation, when performed in a recorder, to happen in one phaser-mediated critical section (so that the combination of counts update and min/max update is properly synchronized against recorder samples).

The use pattern is simple: value recording is concurrent (usually into a recorder), but observing the histogram is single-threaded and performed only on histograms obtained via a recorder sample. A specific example use case I am looking at this for is histogram'ing allocated object sizes and reporting on those histograms periodically.

I think that this can be added quite easily to the current C implementation by adding the following APIs:
hdr_record_value_atomic
hdr_record_values_atomic
hdr_record_corrected_value_atomic
hdr_record_corrected_values_atomic
hdr_interval_recorder_record_value_atomic
hdr_interval_recorder_record_values_atomic
hdr_interval_recorder_record_corrected_value_atomic
hdr_interval_recorder_record_corrected_values_atomic

The implementation details are probably obvious from the above.

**Comment by mikeb01** [comment]
When you say 'atomic', do you need any specific ordering guarantees or do you just need to be able to avoid torn reads?

**Comment by giltene** [comment]
> When you say 'atomic', do you need any specific ordering guarantees or do you just need to be able to avoid torn reads?

Hmm... I guess I'm too used to spec'ing APIs in a world where ordering for such things is actually defined ;-)

What I want it to enable "safe" concurrent value recording to the histogram (most likely via a recorder). I don't think this requires any ordering guarantees internally (e.g. between the atomic increments of the counts and the atomic CAS for the min/max updates).

I'm not sure we care (or not) about what this means to the calling threads from an ordering perspective. We could make them deal with ordering on their side (document the added atomic apis as not having any ordering implications), or we can document them as having ordering semantics (which should probably be aquire+release). I don't have a strong opinion for which is better: I can see an argument for the weaker form (theoretical speed benefit from avoiding ordering requirements), but my gut is to take the strong form (doesn't actually make a difference at the CPU level on e.g. x86, which orders LOCK operations anyway, and harder to make silly mistakes with).

**Comment by mikeb01** [comment]
Okay I think I understand now. Probably take about a week before I get a chance to look at it, should be straight forward though.

**Comment by mikeb01** [comment]
Hi @giltene I've started implementing the atomic recording APIs (just record_value(s)_atomic so far).  Can you take a look and let me know if this is what you are looking for?

**Comment by giltene** [comment]
@mikeb01 yes, looks like the right path.
One perf question: I see that the atomic adds are done via hdr_atomic_add_fetch_64(), and I have not quite tracked the implementation down to verify this devolves to a LOCK XADD on x86. The XADD instruction is actually a fetch_then_add (rather than an add_then_fetch), so while the compiler will likely get rid of the fetch part anyway (when unused), I just want to verify the actual generated code is what we think it is (and not some slower use of CMPX).

**Comment by mikeb01** [comment]
The assembly generated on my laptop looks like it is using XADD.

```
0000000000001c05 <counts_inc_normalised_atomic>:
    1c05:       55                      push   %rbp
    1c06:       48 89 e5                mov    %rsp,%rbp
    1c09:       48 83 ec 28             sub    $0x28,%rsp
    1c0d:       48 89 7d e8             mov    %rdi,-0x18(%rbp)
    1c11:       89 75 e4                mov    %esi,-0x1c(%rbp)
    1c14:       48 89 55 d8             mov    %rdx,-0x28(%rbp)
    1c18:       8b 55 e4                mov    -0x1c(%rbp),%edx
    1c1b:       48 8b 45 e8             mov    -0x18(%rbp),%rax
    1c1f:       89 d6                   mov    %edx,%esi
    1c21:       48 89 c7                mov    %rax,%rdi
    1c24:       e8 a6 fe ff ff          callq  1acf <normalize_index>
    1c29:       89 45 fc                mov    %eax,-0x4(%rbp)
    1c2c:       48 8b 45 d8             mov    -0x28(%rbp),%rax
    1c30:       48 8b 55 e8             mov    -0x18(%rbp),%rdx
    1c34:       48 8b 52 60             mov    0x60(%rdx),%rdx
    1c38:       8b 4d fc                mov    -0x4(%rbp),%ecx
    1c3b:       48 63 c9                movslq %ecx,%rcx
    1c3e:       48 c1 e1 03             shl    $0x3,%rcx
    1c42:       48 01 ca                add    %rcx,%rdx
    1c45:       f0 48 01 02             lock add %rax,(%rdx)
    1c49:       48 8b 45 d8             mov    -0x28(%rbp),%rax
    1c4d:       48 8b 55 e8             mov    -0x18(%rbp),%rdx
    1c51:       48 83 c2 58             add    $0x58,%rdx
    1c55:       f0 48 01 02             lock add %rax,(%rdx)
    1c59:       90                      nop
    1c5a:       c9                      leaveq 
    1c5b:       c3                      retq   
```

**Comment by mikeb01** [comment]
I think this is pretty much implemented now.  Let me know how it works for you.

**Comment by mikeb01** [comment]
I'll make a proper release in the next day or 2 once I'm happy I haven't left any obvious bugs behind.
