### ISSUE TITLE
document hdr_interval_recorder_sample() is "dangerous".

### ISSUE THREAD

**Issue by giltene** [HdrHistogram/HdrHistogram_c#69]
Currently, there are two potential "dangerous" things in hdr_interval_recorder_sample()'s behavior that would not be obvious to the caller without clear documentation: 

- hdr_interval_recorder_sample() is not thread safe when multiple threads may call it (is is still thread-safe for one reader against multiple recorders). E.g. if two readers called the method concurrently, they could both end up receiving the same (2nd) interval sample, and the 1st would be lost.  

- In addition, since the next sample call will recycle the r->inactive histogram returned by this call, a histogram returned by a previous-sample will become active without this being obvious to the caller (who may choose to retain multiple histograms).

In contrast, hdr_interval_recorder_sample_and_recycle is both multi-reader-thread safe, and will only "stomp" the histogram passe to it for recycling (can probably change parameter name there form "inactive_histogram" to "histogram_to_recycle" to make it abundantly clear).

While hdr_interval_recorder_sample does fit the dominant and common use case (single reader, which does not retain a histogram across sample calls), the current API probably needs documentation that would warn-off misuse and spell out the limitations or the implementation should change or dropped.

I believe that the common idiom can be changed from

inactive = hdr_interval_recorder_sample(&recorder);

to the already available:

histogram = hdr_interval_recorder_sample_and_recycle(&recorder, histogram);

This change is quite simple for the caller and does not require any additional code (histogram can be initialized to null at the start), and makes it very clear (in the calling code) that the histogram is being recycled, so that the "wrongness" of using it (the one-handed in for recycling, not the one returned from the sample) after the call is obvious.

**Comment by mikeb01** [comment]
Makes a lot of sense.  I've marked the straight sample method as deprecated.
