### ISSUE TITLE
Please explain tagging strategy

### ISSUE THREAD

**Issue by lzap** [HdrHistogram/HdrHistogram_c#72]
Hello,

I am working on Fedora RPM package and I would like to confirm the tagging strategy. I see two sets of tags, one without prefix and the other with HdrHistogram_c prefix. Which one out of these two is the right one?

I will be downloading releases directly from the github via the tag then.

Thanks!

**Comment by mikeb01** [comment]
The ones **without** the HdrHistogram_c prefix are the correct ones.  I'll add more tags for consistency.

**Comment by lzap** [comment]
Thanks a bunch, my package passed review and it's on the way into Fedora Rawhide and 31!

https://bugzilla.redhat.com/show_bug.cgi?id=1741840
