### ISSUE TITLE
Documentation of the hdr_init

### ISSUE THREAD

**Issue by assaad** [HdrHistogram/HdrHistogram_c#92]
Hello,
I would like to understand a bit more the parameters of the hdr_init, what do these parameters means:
lowest_discernible_value, highest_trackable_value, significant_figures ?
Is there a documentation available somewhere?

Many thanks

**Comment by mikeb01** [comment]
The [header](https://github.com/HdrHistogram/HdrHistogram_c/blob/master/src/hdr_histogram.h#L48) documents each of the parameters.  Is there something specific that is missing from there that would make the meaning of the various parameters clearer.

**Comment by mikeb01** [comment]
Close due to no response.
